runtime: python312
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app

instance_class: F2

env_variables:
  USE_GCS: "true"
  GCS_BUCKET_NAME: "team-bubu"
  BASE_URL: "https://team-bubu.appspot.com"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /images
  static_dir: result
  secure: always

- url: /.*
  script: auto
  secure: always
